### ISSUE TITLE
Registration Request: change-password

### ISSUE THREAD

**Issue by hober** [protocol-registries/well-known-uris#12]
Please confirm that:

* [x] You have read and understood the [requirements for registration](https://tools.ietf.org/html/rfc8615#section-3.1).
* [x] You have checked [the registry](https://www.iana.org/assignments/well-known-uris/) and found no current value that meets your needs.
* [x] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information below.

If so, please provide the details of your request below.

Enter the details of the link relation type below:

* URI suffix: `change-password`
* Change controller: W3C 
* Specification document(s): [A Well-Known URL for Changing Passwords § 4.1. The change-password well-known URI](https://w3c.github.io/webappsec-change-password-url/#the-change-password-well-known-uri)

Any additional information (this will not be included in the registry)? None.

**Comment by mnot** [comment]
Same question as elsewhere - does the WG consider this near done?

**Comment by Saiv46** [comment]
Still waiting for the spec standardization?

**Comment by VojtaStanek** [comment]
Hello. Not from the WG, but this is used in the wild in safari and chrome as shown below. The spec looks done since it wasn't [changed in last two years](https://github.com/w3c/webappsec-change-password-url/commits/main/change-password-url.bs). 

- https://twitter.com/chriscoyier/status/1516937508075933696
- https://web.dev/change-password-url/
- https://webkit.org/blog/9170/safari-technology-preview-84-with-safari-13-features-is-now-available/
- https://github.com/w3c/webappsec-change-password-url#what-tools-have-implemented-this-feature

**Comment by mnot** [comment]
I'm mostly hesitating because this spec isn't listed on the [wg home page](https://www.w3.org/2011/webappsec/).

**Comment by hober** [comment]
> I'm mostly hesitating because this spec isn't listed on the [wg home page](https://www.w3.org/2011/webappsec/).

PR is up to fix that: w3c/webappsec#609

**Comment by mnot** [comment]
Registered. When the spec goes REC, ping me and we'll flip it from 'provisional' to 'standard'.
